/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iziagenda;

import java.awt.Color;
import javax.swing.JComboBox;

/**
 *
 * @author Angelo
 */
public class frmEditarColores extends javax.swing.JFrame {

    /**
     * Creates new form frmEditarColores
     */
    public frmEditarColores()
    {
        initComponents();
        extraClass.centrarFrame(this);
        
        llenarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenerdor = new javax.swing.JPanel();
        lblLogIn = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblCorreo1 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        lblContraseña1 = new javax.swing.JLabel();
        cbTareas = new javax.swing.JComboBox<>();
        cbRecordatorios = new javax.swing.JComboBox<>();
        cbEventos = new javax.swing.JComboBox<>();
        cbExamenes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 460));
        setUndecorated(true);

        pnlContenerdor.setBackground(new java.awt.Color(0, 153, 204));
        pnlContenerdor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlContenerdor.setMaximumSize(new java.awt.Dimension(400, 460));
        pnlContenerdor.setMinimumSize(new java.awt.Dimension(400, 460));
        pnlContenerdor.setPreferredSize(new java.awt.Dimension(400, 460));
        pnlContenerdor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogIn.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        lblLogIn.setForeground(new java.awt.Color(255, 255, 255));
        lblLogIn.setText("Editar colores");
        pnlContenerdor.add(lblLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(37, 116, 169));
        btnGuardar.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlContenerdor.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 320, -1));

        btnVolver.setBackground(new java.awt.Color(37, 116, 169));
        btnVolver.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        pnlContenerdor.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 320, -1));

        lblCorreo1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCorreo1.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo1.setText("Color para tareas:");
        pnlContenerdor.add(lblCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lblCorreo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Color para exámenes:");
        pnlContenerdor.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 280, -1));

        lblContraseña.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setText("Color para eventos:");
        pnlContenerdor.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 300, -1));

        lblContraseña1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblContraseña1.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña1.setText("Color para recordatorios:");
        pnlContenerdor.add(lblContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 290, -1));

        cbTareas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbTareas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTareasItemStateChanged(evt);
            }
        });
        pnlContenerdor.add(cbTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 320, 30));

        cbRecordatorios.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbRecordatorios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRecordatoriosItemStateChanged(evt);
            }
        });
        pnlContenerdor.add(cbRecordatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 320, 30));

        cbEventos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbEventos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEventosItemStateChanged(evt);
            }
        });
        pnlContenerdor.add(cbEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 320, 30));

        cbExamenes.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbExamenes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbExamenesItemStateChanged(evt);
            }
        });
        pnlContenerdor.add(cbExamenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 320, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenerdor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenerdor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //cbImportancia.setSelectedIndex(cbImportancia.getSelectedIndex()-1);
        //cbImportancia.removeAllItems();
        //generarDias();
        guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        volver();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cbTareasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTareasItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbTareasItemStateChanged

    private void cbRecordatoriosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRecordatoriosItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRecordatoriosItemStateChanged

    private void cbEventosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEventosItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEventosItemStateChanged

    private void cbExamenesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbExamenesItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbExamenesItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEditarColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEditarColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEditarColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEditarColores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEditarColores().setVisible(true);
            }
        });
    }

    public void volver()
    {
        this.dispose();
        new frmConfiguracion().setVisible(true);
    }
    
    public void guardar()
    {
        //esto falta y ya está ya; izi izi
        fabricaClass.getUsuarioLogeado().setColorTarea(fabricaClass.colores[cbTareas.getSelectedIndex()]);
        fabricaClass.getUsuarioLogeado().setColorExamen(fabricaClass.colores[cbExamenes.getSelectedIndex()]);
        fabricaClass.getUsuarioLogeado().setColorEvento(fabricaClass.colores[cbEventos.getSelectedIndex()]);
        fabricaClass.getUsuarioLogeado().setColorRecordatorio(fabricaClass.colores[cbRecordatorios.getSelectedIndex()]);
        
        //al final serializa y vuelve como el otro p 
        fabricaClass.serializarDatos();
        volver();
    }
    
    public void llenarDatos()
    {
        //ah esto tmb falta B)
        llenarColores(cbTareas);
        llenarColores(cbExamenes);
        llenarColores(cbEventos);
        llenarColores(cbRecordatorios);
        
        cbTareas.setSelectedItem(nombreDelColor(fabricaClass.getUsuarioLogeado().getColorTarea()));
        cbExamenes.setSelectedItem(nombreDelColor(fabricaClass.getUsuarioLogeado().getColorExamen()));
        cbEventos.setSelectedItem(nombreDelColor(fabricaClass.getUsuarioLogeado().getColorEvento()));
        cbRecordatorios.setSelectedItem(nombreDelColor(fabricaClass.getUsuarioLogeado().getColorRecordatorio()));
    }
    
    public void llenarColores(JComboBox cb)
    {
        for(Color c: fabricaClass.colores)
        {
            cb.addItem(nombreDelColor(c));
        }
    }
    
    public String nombreDelColor(Color c)
    {
        if(c.getRGB()==fabricaClass.amarillo.getRGB())
        {
            return "Amarillo";
        }
        else if(c.getRGB()==fabricaClass.anaranjado.getRGB())
        {
            return "Anaranjado";
        }
        else if(c.getRGB()==fabricaClass.celeste.getRGB())
        {
            return "Celeste";
        }
        else if(c.getRGB()==fabricaClass.fuxia.getRGB())
        {
            return "Fuxia";
        }
        else if(c.getRGB()==fabricaClass.gris.getRGB())
        {
            return "Gris";
        }
        else if(c.getRGB()==fabricaClass.morado.getRGB())
        {
            return "Morado";
        }
        else if(c.getRGB()==fabricaClass.plateado.getRGB())
        {
            return "Plateado";
        }
        else if(c.getRGB()==fabricaClass.rojo.getRGB())
        {
            return "Rojo";
        }
        else if(c.getRGB()==fabricaClass.turquesa.getRGB())
        {
            return "Turquesa";
        }
        else if(c.getRGB()==fabricaClass.verde.getRGB())
        {
            return "Verde";
        }
        else
        {
            return "";
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbEventos;
    private javax.swing.JComboBox<String> cbExamenes;
    private javax.swing.JComboBox<String> cbRecordatorios;
    private javax.swing.JComboBox<String> cbTareas;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblContraseña1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblLogIn;
    private javax.swing.JPanel pnlContenerdor;
    // End of variables declaration//GEN-END:variables
}
