/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iziagenda;

import javax.swing.JOptionPane;

/**
 *
 * @author Angelo
 */
public class frmEditarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frmEditarUsuario
     */
    public frmEditarUsuario()
    {
        initComponents();
        
        extraClass.centrarFrame(this);
        
        llenarDatos();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenerdor = new javax.swing.JPanel();
        lblLogIn = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblCorreo1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 380));
        setMinimumSize(new java.awt.Dimension(400, 380));
        setUndecorated(true);

        pnlContenerdor.setBackground(new java.awt.Color(0, 153, 204));
        pnlContenerdor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlContenerdor.setMaximumSize(new java.awt.Dimension(400, 380));
        pnlContenerdor.setMinimumSize(new java.awt.Dimension(400, 380));
        pnlContenerdor.setPreferredSize(new java.awt.Dimension(400, 380));
        pnlContenerdor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogIn.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        lblLogIn.setForeground(new java.awt.Color(255, 255, 255));
        lblLogIn.setText("Editar usuario");
        pnlContenerdor.add(lblLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(37, 116, 169));
        btnGuardar.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlContenerdor.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 320, -1));

        btnVolver.setBackground(new java.awt.Color(37, 116, 169));
        btnVolver.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        pnlContenerdor.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 320, -1));

        lblCorreo1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCorreo1.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo1.setText("Nombre:");
        pnlContenerdor.add(lblCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        txtNombre.setFont(new java.awt.Font("DialogInput", 0, 16)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        pnlContenerdor.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 320, -1));

        lblCorreo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo:");
        pnlContenerdor.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 70, -1));

        txtCorreo.setFont(new java.awt.Font("DialogInput", 0, 16)); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        pnlContenerdor.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 320, -1));

        lblContraseña.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setText("Contraseña:");
        pnlContenerdor.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        pnlContenerdor.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 320, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenerdor, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContenerdor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        //cbImportancia.setSelectedIndex(cbImportancia.getSelectedIndex()-1);
        //cbImportancia.removeAllItems();
        //generarDias();
        guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        volver();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
        try
        {
            if(txtNombre.getText().length()==0)
            {
                txtNombre.requestFocus();
                throw new Exception ("No deje ningún campo vacío. Ingrese su nombre.");
            }
            txtCorreo.requestFocus();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Datos incorrectos",0);
        }
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
        try
        {
            if(txtCorreo.getText().length()==0)
            {
                txtCorreo.requestFocus();
                throw new Exception ("No deje ningún campo vacío. Ingrese su correo.");
            }
            else if(!fabricaClass.esCorreoValido(txtCorreo.getText()))
            {
                txtCorreo.requestFocus();
                txtCorreo.setText("");
                throw new Exception ("Ingrese un correo válido.");
            }
            else if(fabricaClass.correoYaExiste(txtCorreo.getText()))
            {
                txtCorreo.requestFocus();
                txtCorreo.setText("");
                throw new Exception ("Ya existe una cuenta con este correo. Intente con otro.");
            }
            else
            {
                txtContraseña.requestFocus();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Datos incorrectos",0);
        }
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_txtContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEditarUsuario().setVisible(true);
            }
        });
    }

    public void volver()
    {
        this.dispose();
        new frmConfiguracion().setVisible(true);
    }
    
    public void guardar()
    {
        try
        {
            if(txtNombre.getText().length()==0)
            {
                txtNombre.requestFocus();
                throw new Exception ("No deje ningún campo vacío. Ingrese su nombre.");
            }
            else if(txtCorreo.getText().length()==0)
            {
                txtCorreo.requestFocus();
                throw new Exception ("No deje ningún campo vacío. Ingrese su correo.");
            }
            else if(new String(txtContraseña.getPassword()).length()==0)
            {
                txtContraseña.requestFocus();
                throw new Exception ("No deje ningún campo vacío. Ingrese su contraseña.");
            }
            else if(!fabricaClass.esCorreoValido(txtCorreo.getText()))
            {
                txtCorreo.requestFocus();
                txtCorreo.setText("");
                throw new Exception ("Ingrese un correo válido.");
            }
            else if(fabricaClass.correoYaExiste(txtCorreo.getText()) && !fabricaClass.getUsuarioLogeado().getCorreo().equals(new String(txtCorreo.getText())))
            {
                txtCorreo.requestFocus();
                txtCorreo.setText("");
                throw new Exception ("Ya existe una cuenta con este correo. Intente con otro.");
            }
            else if(new String(txtContraseña.getPassword()).length()<8)
            {
                txtContraseña.requestFocus();
                txtContraseña.setText("");
                throw new Exception ("La contraseña debe tener como mínimo 8 caracteres.");
            }
            else
            {
                //guardar
                fabricaClass.getUsuarioLogeado().modificarDatos(txtNombre.getText(), txtCorreo.getText() , new String (txtContraseña.getPassword()));
                fabricaClass.serializarDatos();
                volver();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Datos incorrectos",0);
        }
    }
    
    public void llenarDatos()
    {
        txtNombre.setText(fabricaClass.getUsuarioLogeado().getNombre());
        txtCorreo.setText(fabricaClass.getUsuarioLogeado().getCorreo());
        txtContraseña.setText(fabricaClass.getUsuarioLogeado().getContraseña());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblLogIn;
    private javax.swing.JPanel pnlContenerdor;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
