/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iziagenda;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class frmLogIn extends javax.swing.JFrame {

    /**
     * Creates new form frmLogIn
     */
    private class Loader extends Thread
    {
        @Override
        public void run()
        {
            new frmLogIn().setVisible(true);
        }
    }
    
    public frmLogIn()
    {
        initComponents();
        extraClass.centrarFrame(this);
        crearAdmin();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogIn = new javax.swing.JPanel();
        lblLogIn = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        cbRecuerdame = new javax.swing.JCheckBox();
        lblOlvidaste = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        lblCreala = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        pnlCabecera = new javax.swing.JPanel();
        lblIziAgenda = new javax.swing.JLabel();
        lblSlogan = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 204));
        setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogIn.setBackground(new java.awt.Color(0, 153, 204));
        pnlLogIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlLogIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogIn.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        lblLogIn.setForeground(new java.awt.Color(255, 255, 255));
        lblLogIn.setText("LogIn");
        pnlLogIn.add(lblLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        txtCorreo.setFont(new java.awt.Font("DialogInput", 0, 16)); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        pnlLogIn.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 321, -1));

        lblCorreo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo:");
        pnlLogIn.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setText("Contraseña:");
        pnlLogIn.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        cbRecuerdame.setBackground(new java.awt.Color(0, 153, 204));
        cbRecuerdame.setForeground(new java.awt.Color(255, 255, 255));
        cbRecuerdame.setText("Recuérdame");
        cbRecuerdame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbRecuerdame.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbRecuerdameItemStateChanged(evt);
            }
        });
        pnlLogIn.add(cbRecuerdame, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        lblOlvidaste.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblOlvidaste.setForeground(new java.awt.Color(255, 255, 255));
        lblOlvidaste.setText("Olvidaste tu contraseña?");
        lblOlvidaste.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOlvidaste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOlvidasteMouseClicked(evt);
            }
        });
        pnlLogIn.add(lblOlvidaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        btnIngresar.setBackground(new java.awt.Color(37, 116, 169));
        btnIngresar.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        pnlLogIn.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 320, -1));

        lblCreala.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblCreala.setForeground(new java.awt.Color(255, 255, 255));
        lblCreala.setText("Aún no tienes una cuenta? Créala ahora.");
        lblCreala.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCreala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCrealaMouseClicked(evt);
            }
        });
        pnlLogIn.add(lblCreala, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        pnlLogIn.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 320, 30));

        getContentPane().add(pnlLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 400, 350));

        pnlCabecera.setBackground(new java.awt.Color(0, 0, 0));
        pnlCabecera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlCabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIziAgenda.setFont(new java.awt.Font("Century Gothic", 0, 55)); // NOI18N
        lblIziAgenda.setForeground(new java.awt.Color(255, 255, 255));
        lblIziAgenda.setText("iziAgenda");
        pnlCabecera.add(lblIziAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        lblSlogan.setFont(new java.awt.Font("DialogInput", 0, 23)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(255, 255, 255));
        lblSlogan.setText("Reorganiza tu vida");
        pnlCabecera.add(lblSlogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        lblMinimizar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimizar.setText("-");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        pnlCabecera.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        lblCerrar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setText("X");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        pnlCabecera.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iziagenda/logo.png"))); // NOI18N
        pnlCabecera.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 80));

        getContentPane().add(pnlCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        //ingresar:
        ingresar();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void lblCrealaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCrealaMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new frmSignUp().setVisible(true);
    }//GEN-LAST:event_lblCrealaMouseClicked

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
        try
        {
            if(txtCorreo.getText().length()==0)
            {
                txtCorreo.requestFocus();
                throw new Exception ("No deje ningún campo vacío. Ingrese su correo.");
            }
            txtContraseña.requestFocus();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Datos incorrectos",0);
        }
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
        ingresar();
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void lblOlvidasteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvidasteMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new frmOlvidoCuenta().setVisible(true);
    }//GEN-LAST:event_lblOlvidasteMouseClicked

    private void cbRecuerdameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbRecuerdameItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbRecuerdameItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if(hayUsuarioRecordado())
        {
            this.dispose();
            new frmPrincipal().setVisible(true);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogIn().setVisible(true);
            }
        });
    }
    
    public void ingresar()
    {
        try
        {
            if(txtCorreo.getText().equals("admin")&&new String(txtContraseña.getPassword()).equals("123"))
            {
                if(fabricaClass.logIn("iziagenda.adm@gmail.com", "12345678"))
                {
                    if(cbRecuerdame.isSelected())
                    {
                        fabricaClass.getUsuarioLogeado().setRecordado(true);
                        fabricaClass.serializarDatos();
                    }
                    this.dispose();
                    new frmPrincipal().setVisible(true);
                }
                return;
            }
            if(txtCorreo.getText().length()==0)
            {
                txtCorreo.requestFocus();
                throw new Exception ("No deje ningún campo vacío. Ingrese su correo.");
            }
            
            else if(new String(txtContraseña.getPassword()).length()==0)
            {
                txtContraseña.requestFocus();
                throw new Exception ("No deje ningún campo vacío. Ingrese su contraseña.");
            }
            else
            {
                //INGRESA
                if(fabricaClass.logIn(txtCorreo.getText(), new String(txtContraseña.getPassword())))
                {
                    if(cbRecuerdame.isSelected())
                    {
                        fabricaClass.getUsuarioLogeado().setRecordado(true);
                        fabricaClass.serializarDatos();
                    }
                    this.dispose();
                    new frmPrincipal().setVisible(true);
                }
                else
                {
                    txtCorreo.setText("");
                    txtContraseña.setText("");
                    txtCorreo.requestFocus();
                    throw new Exception ("Correo o contraseña incorrectos.");
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Datos incorrectos",0);
        }
    }
    public void crearAdmin()
    {
        if(adminExiste()==false)
        {
            fabricaClass.agregarUsuario(new usuarioClass("Administrador","iziagenda.adm@gmail.com","12345678"));
            fabricaClass.serializarDatos();
        }
    }
    
    public boolean adminExiste()
    {
        boolean existe = false;
        for(usuarioClass user : fabricaClass.getUsuarios())
        {
            //System.out.println(user.getCorreo());
            if(user.getCorreo().equals("iziagenda.adm@gmail.com"))
            {
                existe=true;
                System.out.println("xd");
                break;
            }

        }
        return existe;
    }
    
    public boolean hayUsuarioRecordado()
    {
        boolean h=false;
        for(usuarioClass user: fabricaClass.getUsuarios())
        {
            if(user.getRecordado()==true)
               
            {
                h=true;
                fabricaClass.setUsuarioLogeado(user);
                break;
            }
        }
        /*
        if(usuarioClass.getRecordar())
        {
            fabricaClass.setUsuarioLogeado(usuarioClass.getUsuarioRecordado());
            return true;
        }
        else
        {
            System.out.println("prueba");
            return false;
        }*/
        return h;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JCheckBox cbRecuerdame;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCreala;
    private javax.swing.JLabel lblIziAgenda;
    private javax.swing.JLabel lblLogIn;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblOlvidaste;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlLogIn;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
