/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iziagenda;

import javax.swing.JFrame;

/**
 *
 * @author Angelo
 */
public class frmOlvidoCuenta extends javax.swing.JFrame {

    /**
     * Creates new form frmOlvidoCuenta
     */
    public frmOlvidoCuenta() {
        initComponents();
        extraClass.centrarFrame(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCabecera = new javax.swing.JPanel();
        lblIziAgenda = new javax.swing.JLabel();
        lblSlogan = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        pnlLogIn = new javax.swing.JPanel();
        lblLogIn = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblLogIn1 = new javax.swing.JLabel();
        lblLogIn2 = new javax.swing.JLabel();
        btnContactar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 510));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCabecera.setBackground(new java.awt.Color(0, 0, 0));
        pnlCabecera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlCabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIziAgenda.setFont(new java.awt.Font("Century Gothic", 0, 55)); // NOI18N
        lblIziAgenda.setForeground(new java.awt.Color(255, 255, 255));
        lblIziAgenda.setText("iziAgenda");
        pnlCabecera.add(lblIziAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        lblSlogan.setFont(new java.awt.Font("DialogInput", 0, 23)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(255, 255, 255));
        lblSlogan.setText("Reorganiza tu vida");
        pnlCabecera.add(lblSlogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        lblMinimizar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimizar.setText("-");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        pnlCabecera.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        lblCerrar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setText("X");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        pnlCabecera.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iziagenda/logo.png"))); // NOI18N
        pnlCabecera.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 80));

        getContentPane().add(pnlCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 160));

        pnlLogIn.setBackground(new java.awt.Color(0, 153, 204));
        pnlLogIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlLogIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogIn.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblLogIn.setForeground(new java.awt.Color(255, 255, 255));
        lblLogIn.setText("al administrador");
        pnlLogIn.add(lblLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        btnVolver.setBackground(new java.awt.Color(37, 116, 169));
        btnVolver.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        pnlLogIn.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 320, -1));

        lblLogIn1.setFont(new java.awt.Font("Century Gothic", 3, 18)); // NOI18N
        lblLogIn1.setForeground(new java.awt.Color(255, 255, 255));
        lblLogIn1.setText("Parece que olvidaste tu contraseña");
        pnlLogIn.add(lblLogIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        lblLogIn2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblLogIn2.setForeground(new java.awt.Color(255, 255, 255));
        lblLogIn2.setText("Por favor contacta");
        pnlLogIn.add(lblLogIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        btnContactar.setBackground(new java.awt.Color(37, 116, 169));
        btnContactar.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        btnContactar.setForeground(new java.awt.Color(255, 255, 255));
        btnContactar.setText("Contactar");
        btnContactar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnContactar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnContactar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactarActionPerformed(evt);
            }
        });
        pnlLogIn.add(btnContactar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 320, -1));

        getContentPane().add(pnlLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 400, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new frmLogIn().setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnContactarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactarActionPerformed
        // TODO add your handling code here:
        extraClass.abrirUrl("https://www.facebook.com/AngeloLicetti");
    }//GEN-LAST:event_btnContactarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOlvidoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOlvidoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOlvidoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOlvidoCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmOlvidoCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContactar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblIziAgenda;
    private javax.swing.JLabel lblLogIn;
    private javax.swing.JLabel lblLogIn1;
    private javax.swing.JLabel lblLogIn2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlLogIn;
    // End of variables declaration//GEN-END:variables
}
