/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iziagenda;

import java.applet.AudioClip;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author alumno
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    
    private PendienteClass.Tipo tipoMostrado;
    
    Timer timy;
    
    TimerTask cosmo;
    
    public Color colorSeleccionado = new Color(51,11,169);
    public Color colorDeseleccionado = new Color(0,153,204);
   
    URL url;
    
    AudioClip ac;
    
    private frmPrincipal esteFormulario = this;
    
    public frmPrincipal()
    {
        try
        {
            initComponents();
            extraClass.centrarFrame(this);
            
            inicializarAlarma();
            //extraClass.cambiarFondoChido(btnAgregar);
            mostrarNombre();
            iniciarFechaYHora();
            //mostrarTodo();
            presionoMes();
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Adevertencia", 1);
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCabecera = new javax.swing.JPanel();
        lblIziAgenda = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblBienvenido1 = new javax.swing.JLabel();
        pnlContenedor = new javax.swing.JPanel();
        pnlVista = new javax.swing.JPanel();
        lblVista = new javax.swing.JLabel();
        btnMes = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();
        pnlParche = new javax.swing.JPanel();
        lblFecha1 = new javax.swing.JLabel();
        btnDia = new javax.swing.JButton();
        pnlBotones = new javax.swing.JPanel();
        btnVer = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnRanking = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnExtra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCabecera.setBackground(new java.awt.Color(0, 0, 0));
        pnlCabecera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlCabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIziAgenda.setFont(new java.awt.Font("Century Gothic", 0, 60)); // NOI18N
        lblIziAgenda.setForeground(new java.awt.Color(255, 255, 255));
        lblIziAgenda.setText("iziAgenda");
        lblIziAgenda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblIziAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIziAgendaMouseClicked(evt);
            }
        });
        pnlCabecera.add(lblIziAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 80));

        lblMinimizar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimizar.setText("-");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        pnlCabecera.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, -1, -1));

        lblCerrar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setText("X");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        pnlCabecera.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iziagenda/logo.png"))); // NOI18N
        lblLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoMouseClicked(evt);
            }
        });
        pnlCabecera.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        lblNombre.setFont(new java.awt.Font("DialogInput", 3, 36)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre Apellido Apellido");
        pnlCabecera.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, -1));

        lblBienvenido1.setFont(new java.awt.Font("DialogInput", 3, 24)); // NOI18N
        lblBienvenido1.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenido1.setText("Bienvenido (a),");
        pnlCabecera.add(lblBienvenido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        getContentPane().add(pnlCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, -1));

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlContenedor.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(pnlContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 1180, 580));

        pnlVista.setBackground(new java.awt.Color(0, 153, 204));
        pnlVista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlVista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVista.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblVista.setText("Vista:");
        pnlVista.add(lblVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnMes.setBackground(new java.awt.Color(37, 116, 169));
        btnMes.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        btnMes.setForeground(new java.awt.Color(255, 255, 255));
        btnMes.setText("Mes");
        btnMes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnMes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesActionPerformed(evt);
            }
        });
        pnlVista.add(btnMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 140, 30));

        lblFecha.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblFecha.setText("Domingo, ## de Septiembre del 0123  01:23:45");
        pnlVista.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 560, -1));

        pnlParche.setBackground(new java.awt.Color(0, 153, 204));

        lblFecha1.setBackground(new java.awt.Color(0, 153, 204));
        lblFecha1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblFecha1.setForeground(new java.awt.Color(0, 153, 204));
        lblFecha1.setText("Fecha y hora de hoy:");

        btnDia.setBackground(new java.awt.Color(0, 153, 204));
        btnDia.setFont(new java.awt.Font("Consolas", 0, 30)); // NOI18N
        btnDia.setForeground(new java.awt.Color(255, 255, 255));
        btnDia.setText("Día");
        btnDia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnDia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlParcheLayout = new javax.swing.GroupLayout(pnlParche);
        pnlParche.setLayout(pnlParcheLayout);
        pnlParcheLayout.setHorizontalGroup(
            pnlParcheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParcheLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFecha1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        pnlParcheLayout.setVerticalGroup(
            pnlParcheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParcheLayout.createSequentialGroup()
                .addGroup(pnlParcheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha1)
                    .addComponent(btnDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlVista.add(pnlParche, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 30));

        getContentPane().add(pnlVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 1180, 50));

        pnlBotones.setBackground(new java.awt.Color(37, 116, 169));
        pnlBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVer.setBackground(new java.awt.Color(0, 153, 204));
        btnVer.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnVer.setForeground(new java.awt.Color(255, 255, 255));
        btnVer.setText("VER");
        btnVer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        pnlBotones.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 90));

        btnAgregar.setBackground(new java.awt.Color(0, 153, 204));
        btnAgregar.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("AGREGAR");
        btnAgregar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 90, 90));

        btnConfiguracion.setBackground(new java.awt.Color(0, 153, 204));
        btnConfiguracion.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnConfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        btnConfiguracion.setText("CONFIG");
        btnConfiguracion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });
        pnlBotones.add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 90, 90));

        btnBuscar.setBackground(new java.awt.Color(0, 153, 204));
        btnBuscar.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 90, 90));

        btnRanking.setBackground(new java.awt.Color(0, 153, 204));
        btnRanking.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnRanking.setForeground(new java.awt.Color(255, 255, 255));
        btnRanking.setText("RANKING");
        btnRanking.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnRanking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        pnlBotones.add(btnRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 90, 90));

        btnCerrarSesion.setBackground(new java.awt.Color(0, 153, 204));
        btnCerrarSesion.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("SALIR");
        btnCerrarSesion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 90, 90));

        btnExtra.setBackground(new java.awt.Color(0, 153, 204));
        btnExtra.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        btnExtra.setForeground(new java.awt.Color(255, 255, 255));
        btnExtra.setText("AYUDA");
        btnExtra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnExtra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraActionPerformed(evt);
            }
        });
        pnlBotones.add(btnExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 90, 90));

        getContentPane().add(pnlBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 90, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        fabricaClass.getUsuarioLogeado().setRecordado(false);
        fabricaClass.serializarDatos();
        cerrarSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new frmElegirPendiente().setVisible(true);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraActionPerformed
        // TODO add your handling code here:
        extraClass.abrirUrl("https://www.facebook.com/AngeloLicetti");
    }//GEN-LAST:event_btnExtraActionPerformed

    private void btnMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesActionPerformed
        // TODO add your handling code here:
        presionoMes();
    }//GEN-LAST:event_btnMesActionPerformed

    private void btnDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiaActionPerformed
        // TODO add your handling code here:
        presionoDia();
    }//GEN-LAST:event_btnDiaActionPerformed

    private void lblLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoMouseClicked
        // TODO add your handling code here:
        extraClass.abrirUrl("https://www.youtube.com/channel/UCAR-NnNNF2lkuVGsQTuiauQ");
    }//GEN-LAST:event_lblLogoMouseClicked

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        presionoMes();
    }//GEN-LAST:event_btnVerActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        timy.cancel();
    }//GEN-LAST:event_formWindowClosed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new frmRanking().setVisible(true);
    }//GEN-LAST:event_btnRankingActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new frmConfiguracion().setVisible(true);
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void lblIziAgendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIziAgendaMouseClicked
        // TODO add your handling code here:
        if(fabricaClass.adminLogeado())
        {
            int confirmar = JOptionPane.showConfirmDialog(this, (String)"Todos los usuarios se eliminarán permanentemente. ¿Desea continuar?" , "¡Atención!", 2, 2);
            if(confirmar==0)
            {
                fabricaClass.setUsuarios(new ArrayList<usuarioClass>());
                fabricaClass.logOut();
                
                fabricaClass.serializarDatos();
                this.dispose();
                new frmLogIn().setVisible(true);
            }
        }
    }//GEN-LAST:event_lblIziAgendaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    
    private void mostrarNombre()
    {
        lblNombre.setText(fabricaClass.getUsuarioLogeado().getNombre());
    }
    
    private void mostrarTodo()
    {
        //pnlListaDePendientes.removeAll();
        for(PendienteClass pendiente : fabricaClass.getUsuarioLogeado().getPendientes())
        {
            JPanel panel = new pnlPendiente(pendiente);
            
            panel.addMouseListener(new java.awt.event.MouseAdapter()
            {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt)
                {
                    pendienteSeleccionadoMouseClicked(pendiente);
                }
            }
            );
            /*
            ((pnlPendiente)(panel)).getBtnEditar().addMouseListener(new java.awt.event.MouseAdapter()
            {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt)
                {
                    editarPendiente(pendiente);
                }
            }
            );*/
                
            ((pnlPendiente)(panel)).getBtnEliminar().addMouseListener(new java.awt.event.MouseAdapter()
            {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt)
                {
                    eliminarPendiente(pendiente);
                }
            }
            );    
            //pnlListaDePendientes.add(panel);
            //pnlListaDePendientes.add(new pnlPendiente(pendiente));
        }
        tipoMostrado = PendienteClass.Tipo.TODO;
        //pnlListaDePendientes.updateUI();
    }
    
    private void mostrarSolo(PendienteClass.Tipo tipo)
    {
        //pnlListaDePendientes.removeAll();
        for(PendienteClass pendiente : fabricaClass.getUsuarioLogeado().getPendientes())
        {
            if(pendiente.getTipo()== tipo)
            {
                JPanel panel = new pnlPendiente(pendiente);
                
                panel.addMouseListener(new java.awt.event.MouseAdapter()
                {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        pendienteSeleccionadoMouseClicked(pendiente);
                    }
                }
                );
                /*
                ((pnlPendiente)(panel)).getBtnEditar().addMouseListener(new java.awt.event.MouseAdapter()
                {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        editarPendiente(pendiente);
                    }
                }
                );
                
                ((pnlPendiente)(panel)).getBtnEliminar().addMouseListener(new java.awt.event.MouseAdapter()
                {
                    @Override
                    public void mouseClicked(java.awt.event.MouseEvent evt)
                    {
                        eliminarPendiente(pendiente);
                    }
                }
                );
                */
                //pnlListaDePendientes.add(panel);
            }
           
        }
        tipoMostrado = tipo;
        //pnlListaDePendientes.updateUI();
    }
    
    private void pendienteSeleccionadoMouseClicked(PendienteClass pendiente)
    {
        
        fabricaClass.setPendienteSeleccionado(pendiente);
        if(fabricaClass.getPendienteSeleccionado()!=null)
        {
            //txaDatos.setText(fabricaClass.getPendienteSeleccionado().imprimirDatos());
            //txaDetalles.setText(fabricaClass.getPendienteSeleccionado().getDetalles());
        }
        else
        {
            //txaDatos.setText("Funciona pero no");
            //txaDetalles.setText("No has seleccionado nada");
        }
    }
    
    private void editarPendiente(PendienteClass pendiente)
    {
        System.out.println("Pendiente editado: "+pendiente.getNombre());
    }

    private void eliminarPendiente(PendienteClass pendiente)
    {
        int confirmar = JOptionPane.showConfirmDialog(this, (String)"¿Seguro que desea eliminar el pendiente " + pendiente.getNombre() + "?" , "¡Atención!", 2, 2);
        if(confirmar==0)
        {
            
            fabricaClass.getUsuarioLogeado().getPendientes().remove(pendiente);
            fabricaClass.serializarDatos();
            if(tipoMostrado == PendienteClass.Tipo.TODO)mostrarTodo();
            else mostrarSolo(tipoMostrado);
            //txaDatos.setText("");
            //txaDetalles.setText("");
        }
    }
    
    public void cerrarSesion()
    {
        this.dispose();
        fabricaClass.logOut();
        new frmLogIn().setVisible(true);
    }
    
    public void iniciarFechaYHora()
    {
        timy = new Timer();
        cosmo = new TimerTask() {
            @Override
            public void run() {
                actualizarFechaYHora();
            }
        };
        timy.scheduleAtFixedRate(cosmo, 0, 1000);
        
    }
    
    public void actualizarFechaYHora()
    {
        fabricaClass.fechaActual = new GregorianCalendar();
        lblFecha.setText(fabricaClass.imprimirFechaYHora(fabricaClass.fechaActual));
        
        verificarAlarma();
    }
    
    public void mostrarCalendario()
    {
        pnlContenedor.removeAll();
        pnlCalendario cal = new pnlCalendario(fabricaClass.getUsuarioLogeado().getPendientes(),this)
        /*{
            @Override
            public void agregarOidores()
            {
                agregarListeners(cal);
            }
        }*/;
        
        agregarListeners(cal);
        /*
        cal.getCalendar().addMouseListener(new java.awt.event.MouseAdapter()
                        {
                            @Override
                            public void mouseClicked(java.awt.event.MouseEvent evt)
                            {
                                pnlContenedor.removeAll();
                                pnlMostrarDia pnlMD =new pnlMostrarDia(fabricaClass.getUsuarioLogeado().getPendientes(),cal.fechaClickeada);
                                pnlContenedor.add(pnlMD);
                                pnlContenedor.updateUI();
                            }
                        }
                    );*/
        
        pnlContenedor.add(cal);
        pnlContenedor.updateUI();
    }
    
    public void mostrarDia()
    {
        pnlContenedor.removeAll();
        pnlContenedor.add(new pnlMostrarDia(fabricaClass.getUsuarioLogeado().getPendientes(),fabricaClass.fechaActual, this) );
    }
    
    public void mostrarDia(GregorianCalendar gc)
    {
        pnlContenedor.removeAll();
        pnlContenedor.add(new pnlMostrarDia(fabricaClass.getUsuarioLogeado().getPendientes(),gc, this) );
    }
    
    public void presionoMes()
    {
        btnMes.setBackground(colorSeleccionado);
        btnDia.setBackground(colorDeseleccionado);
        pnlVista.repaint();
        mostrarCalendario();
    }
    
    public void presionoDia()
    {
        btnDia.setBackground(colorSeleccionado);
        btnMes.setBackground(colorDeseleccionado);
        pnlVista.repaint();
        mostrarDia();
    }
    
    public void inicializarAlarma()
    {
        try
        {
            url = this.getClass().getResource(fabricaClass.getUsuarioLogeado().getUrlCancionAlarma());
            //System.out.println(fabricaClass.getUsuarioLogeado().getUrlCancionAlarma());
            ac =  alarmaAplet.newAudioClip(url);
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    public void verificarAlarma()
    {
        try
        {
            if(!fabricaClass.getUsuarioLogeado().getPendientes().isEmpty())
            {
                for(PendienteClass pendiente: fabricaClass.getUsuarioLogeado().getPendientes())
                {
                    if(pendiente.getHecho()==true)continue;

                    long s1, s2, diferencia;

                    s1 = (new GregorianCalendar().getTimeInMillis());

                    s2 = (pendiente.getParaCuando().getTimeInMillis());

                    if(s1>s2)
                    {
                        activarAlarmaPendiente(pendiente);
                        break;
                    }
                }
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
            
    }
    
    public void activarAlarmaPendiente(PendienteClass pendiente)
    {
        //ac.play();
        this.dispose();
        new frmAlarmaPendiente(pendiente).setVisible(true);
    }
    public void agregarListeners(pnlCalendario cal)
    {
        
        for(pnlDia pnlD : cal.pnlDias())
        {
            pnlD.addMouseListener(new java.awt.event.MouseAdapter()
                        {
                            @Override
                            public void mouseClicked(java.awt.event.MouseEvent evt)
                            {
                                if(pnlD.tieneDia())
                                {
                                    int d = pnlD.numDia();
                                    int año = Integer.parseInt((String)cal.getCbAño().getSelectedItem());
                                    int mes = cal.getCbMes().getSelectedIndex();
                                    GregorianCalendar xd = new GregorianCalendar(año,mes,d);
                                    
                                    pnlContenedor.removeAll();
                                    pnlMostrarDia pnlMD =new pnlMostrarDia(fabricaClass.getUsuarioLogeado().getPendientes(),xd, esteFormulario);
                                    pnlContenedor.add(pnlMD);
                                    pnlContenedor.updateUI();
                                    
                                    btnDia.setBackground(colorSeleccionado);
                                    btnMes.setBackground(colorDeseleccionado);
                                }
                            }
                        }
                    );
        }
    }
    
    public void buscar()
    {
        if(fabricaClass.getUsuarioLogeado().getPendientes().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "No tienes ninguna actividad pendiente aún.", "Ups!", 1);
        }
        else
        {
            boolean encontrado=false;
            String buscado = JOptionPane.showInputDialog(this, "Ingresa el nombre, o parte del nombre, de la actividad que buscas:");
            System.out.println(buscado);
            if(buscado!=null&&!(buscado.length()==0))
            {
                for(PendienteClass pendiente:fabricaClass.getUsuarioLogeado().getPendientes())
                {
                    if(pendiente.getNombre().contains(buscado))
                    {
                        //System.out.println(pendiente.getNombre());
                        encontrado=true;
                        pnlContenedor.removeAll();
                        pnlContenedor.add(new pnlMostrarDia(fabricaClass.getUsuarioLogeado().getPendientes(),pendiente.getParaCuando(), this));
                        btnDia.setBackground(colorSeleccionado);
                        btnMes.setBackground(colorDeseleccionado);
                        pnlVista.repaint();
                        break;
                    }
                }
            
                if(encontrado==false)
                {
                    JOptionPane.showMessageDialog(this, "No se encontró ninguna actividad pendiente con dicho nombre.", "Sigue intentando!", 1);
                }
            }
        }
            
    }
    
    public JButton getBtnMes()
    {
        return btnMes;
    }
    
    public JButton getBtnDia()
    {
        return btnDia;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnDia;
    private javax.swing.JButton btnExtra;
    private javax.swing.JButton btnMes;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel lblBienvenido1;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblIziAgenda;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblVista;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlParche;
    private javax.swing.JPanel pnlVista;
    // End of variables declaration//GEN-END:variables
}
