/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iziagenda;

import javax.swing.JOptionPane;

/**
 *
 * @author Angelo
 */
public class frmRanking extends javax.swing.JFrame {

    /**
     * Creates new form frmRanking
     */
    public frmRanking()
    {
        initComponents();
        extraClass.centrarFrame(this);
        
        ordenarUsuarios();
        
        agregarUsuarios();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogIn = new javax.swing.JPanel();
        lblComoFunciona = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        spListaPendientes = new javax.swing.JScrollPane();
        pnlUsuarios = new javax.swing.JPanel();
        lblYaPaso1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(510, 550));
        setUndecorated(true);

        pnlLogIn.setBackground(new java.awt.Color(0, 153, 204));
        pnlLogIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlLogIn.setMinimumSize(new java.awt.Dimension(510, 550));
        pnlLogIn.setPreferredSize(new java.awt.Dimension(510, 550));
        pnlLogIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblComoFunciona.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        lblComoFunciona.setForeground(new java.awt.Color(204, 204, 204));
        lblComoFunciona.setText("*¿Cómo funciona?");
        lblComoFunciona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblComoFunciona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblComoFuncionaMouseClicked(evt);
            }
        });
        pnlLogIn.add(lblComoFunciona, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        btnVolver.setBackground(new java.awt.Color(37, 116, 169));
        btnVolver.setFont(new java.awt.Font("Century Gothic", 3, 36)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        pnlLogIn.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 420, 50));

        spListaPendientes.setBorder(null);
        spListaPendientes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlUsuarios.setBackground(new java.awt.Color(0, 153, 204));
        pnlUsuarios.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        pnlUsuarios.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlUsuarios.setLayout(new javax.swing.BoxLayout(pnlUsuarios, javax.swing.BoxLayout.Y_AXIS));
        spListaPendientes.setViewportView(pnlUsuarios);

        pnlLogIn.add(spListaPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 470, 390));

        lblYaPaso1.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        lblYaPaso1.setForeground(new java.awt.Color(255, 255, 255));
        lblYaPaso1.setText("Ranking por puntaje");
        pnlLogIn.add(lblYaPaso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new frmPrincipal().setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void lblComoFuncionaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblComoFuncionaMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Todos los usuarios inician con 0 puntos. Cada actividad que has marcado como ya hecha te suma la importancia de dicha actividad a tu puntaje total.", "¿Cómo obtengo mi puntaje?", 1);
    }//GEN-LAST:event_lblComoFuncionaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRanking().setVisible(true);
            }
        });
    }
    
    public void ordenarUsuarios()
    {
        fabricaClass.ordenarUsuarios();
        fabricaClass.serializarDatos();
    }
    
    public void agregarUsuarios()
    {
        pnlUsuarios.removeAll();
        int n=1;
        for(usuarioClass user : fabricaClass.getUsuarios())
        {
            if(user.getNombre()=="Administrador")
            {
                System.out.println("xdxd");
            }
            pnlUsuarios.add(new pnlUsuario(user, n));
            n++;
        }
        pnlUsuarios.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblComoFunciona;
    private javax.swing.JLabel lblYaPaso1;
    private javax.swing.JPanel pnlLogIn;
    private javax.swing.JPanel pnlUsuarios;
    private javax.swing.JScrollPane spListaPendientes;
    // End of variables declaration//GEN-END:variables
}
