/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iziagenda;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Angelo
 */
public class frmSignUp extends javax.swing.JFrame {

    /**
     * Creates new form frmSignUp
     */
    public frmSignUp() {
        initComponents();
        extraClass.centrarFrame(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        lblSignUp = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        lblLogIn = new javax.swing.JLabel();
        lblContraseña1 = new javax.swing.JLabel();
        lblCorreo1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtRepetirContraseña = new javax.swing.JPasswordField();
        txtContraseña = new javax.swing.JPasswordField();
        pnlCabecera = new javax.swing.JPanel();
        lblIziAgenda = new javax.swing.JLabel();
        lblSlogan = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        lblCerrar = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogin.setBackground(new java.awt.Color(0, 153, 204));
        pnlLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSignUp.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        lblSignUp.setForeground(new java.awt.Color(255, 255, 255));
        lblSignUp.setText("SignUp");
        pnlLogin.add(lblSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        txtCorreo.setFont(new java.awt.Font("DialogInput", 0, 16)); // NOI18N
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        pnlLogin.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 310, -1));

        lblCorreo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo.setText("Correo:");
        pnlLogin.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 70, -1));

        lblContraseña.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setText("Contraseña:");
        pnlLogin.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        btnCrear.setBackground(new java.awt.Color(37, 116, 169));
        btnCrear.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear");
        btnCrear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        pnlLogin.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 310, -1));

        lblLogIn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblLogIn.setForeground(new java.awt.Color(255, 255, 255));
        lblLogIn.setText("Ya tienes una cuenta? Ingresa ahora.");
        lblLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogInMouseClicked(evt);
            }
        });
        pnlLogin.add(lblLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        lblContraseña1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblContraseña1.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña1.setText("Repetir contraseña:");
        pnlLogin.add(lblContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 180, -1));

        lblCorreo1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCorreo1.setForeground(new java.awt.Color(255, 255, 255));
        lblCorreo1.setText("Nombre:");
        pnlLogin.add(lblCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        txtNombre.setFont(new java.awt.Font("DialogInput", 0, 16)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        pnlLogin.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 310, -1));

        txtRepetirContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepetirContraseñaActionPerformed(evt);
            }
        });
        pnlLogin.add(txtRepetirContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 310, 30));

        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        pnlLogin.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 310, 30));

        getContentPane().add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 400, 440));

        pnlCabecera.setBackground(new java.awt.Color(0, 0, 0));
        pnlCabecera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pnlCabecera.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIziAgenda.setFont(new java.awt.Font("Century Gothic", 0, 55)); // NOI18N
        lblIziAgenda.setForeground(new java.awt.Color(255, 255, 255));
        lblIziAgenda.setText("iziAgenda");
        pnlCabecera.add(lblIziAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        lblSlogan.setFont(new java.awt.Font("DialogInput", 0, 23)); // NOI18N
        lblSlogan.setForeground(new java.awt.Color(255, 255, 255));
        lblSlogan.setText("Reorganiza tu vida");
        pnlCabecera.add(lblSlogan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        lblMinimizar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimizar.setText("-");
        lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizarMouseClicked(evt);
            }
        });
        pnlCabecera.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        lblCerrar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblCerrar.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrar.setText("X");
        lblCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });
        pnlCabecera.add(lblCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iziagenda/logo.png"))); // NOI18N
        pnlCabecera.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 80));

        getContentPane().add(pnlCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogInMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new frmLogIn().setVisible(true);
    }//GEN-LAST:event_lblLogInMouseClicked

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        crear();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
        try
        {
            if(txtNombre.getText().length()==0)
            {
                txtNombre.requestFocus();
                throw new Exception ("No deje ningún campo vacío. Ingrese su nombre.");
            }
            txtCorreo.requestFocus();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Datos incorrectos",0);
        }
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
        try
        {
            if(txtCorreo.getText().length()==0)
            {
                txtCorreo.requestFocus();
                throw new Exception ("No deje ningún campo vacío. Ingrese su correo.");
            }
            else if(!fabricaClass.esCorreoValido(txtCorreo.getText()))
            {
                txtCorreo.requestFocus();
                txtCorreo.setText("");
                throw new Exception ("Ingrese un correo válido.");
            }
            else if(fabricaClass.correoYaExiste(txtCorreo.getText()))
            {
                txtCorreo.requestFocus();
                txtCorreo.setText("");
                throw new Exception ("Ya existe una cuenta con este correo. Intente con otro.");
            }
            else
            {
                txtContraseña.requestFocus();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Datos incorrectos",0);
        }
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
        try
        {
            if(new String(txtContraseña.getPassword()).length()==0)
            {
                txtContraseña.requestFocus();
                throw new Exception ("No deje ningún campo vacío. Ingrese su contraseña.");
            }
            else if(new String(txtContraseña.getPassword()).length()<8)
            {
                txtContraseña.requestFocus();
                txtContraseña.setText("");
                txtRepetirContraseña.setText("");
                throw new Exception ("La contraseña debe tener como mínimo 8 caracteres.");
            }
            else
            {
                txtRepetirContraseña.requestFocus();
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Datos incorrectos",0);
        }
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void txtRepetirContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepetirContraseñaActionPerformed
        // TODO add your handling code here:
        crear();
    }//GEN-LAST:event_txtRepetirContraseñaActionPerformed

    private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizarMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSignUp().setVisible(true);
            }
        });
    }
    
    public void crear()
    {
        //CREAR:
        try
        {
            if(txtNombre.getText().length()==0)
            {
                txtNombre.requestFocus();
                throw new Exception ("No deje ningún campo vacío. Ingrese su nombre.");
            }
            else if(txtCorreo.getText().length()==0)
            {
                txtCorreo.requestFocus();
                throw new Exception ("No deje ningún campo vacío. Ingrese su correo.");
            }
            else if(new String(txtContraseña.getPassword()).length()==0)
            {
                txtContraseña.requestFocus();
                throw new Exception ("No deje ningún campo vacío. Ingrese su contraseña.");
            }
            else if(new String(txtRepetirContraseña.getPassword()).length()==0)
            {
                txtRepetirContraseña.requestFocus();
                throw new Exception ("No deje ningún campo vacío. Repita su contraseña.");
            }
            else if(!fabricaClass.esCorreoValido(txtCorreo.getText()))
            {
                txtCorreo.requestFocus();
                txtCorreo.setText("");
                throw new Exception ("Ingrese un correo válido.");
            }
            else if(fabricaClass.correoYaExiste(txtCorreo.getText()))
            {
                txtCorreo.requestFocus();
                txtCorreo.setText("");
                throw new Exception ("Ya existe una cuenta con este correo. Intente con otro.");
            }
            else if(new String(txtContraseña.getPassword()).length()<8)
            {
                txtContraseña.requestFocus();
                txtContraseña.setText("");
                txtRepetirContraseña.setText("");
                throw new Exception ("La contraseña debe tener como mínimo 8 caracteres.");
            }
            else if(!(new String(txtContraseña.getPassword()).equals(new String(txtRepetirContraseña.getPassword()))))
            {
                txtContraseña.requestFocus();
                txtContraseña.setText("");
                txtRepetirContraseña.setText("");
                throw new Exception ("Las contraseñas no coinciden.");
            }
            else
            {
                //CREAR
                fabricaClass.agregarUsuario(new usuarioClass(txtNombre.getText(),txtCorreo.getText(),new String(txtContraseña.getPassword())));
                
                JOptionPane.showMessageDialog(this, "Te has registrado satisfactoriamente.","Bien hecho!",1);
                String corr = txtCorreo.getText();
                this.dispose();
                fabricaClass.serializarDatos();
                String bienvenida ="Hola "+txtNombre.getText()+"!\n\n Nos alegramos de que te hayas unido a iziAgenda.\n"
                        + "Si tienes cualquier duda o consulta estaremos encantados de ayudarte cuando envíes un mensaje a esta dirección."
                        + "\n\nRecuerda: iziAgenda - reoganiza tu vida."
                        + "\n\nAngelo Licetti Leon. Administrador de iziAgenda.";
                try
                {
                    fabricaClass.enviarCorreo(corr, "Bienvenido(a) a iziAgenda.", bienvenida);
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }
                new frmLogIn().setVisible(true);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Datos incorrectos",0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblContraseña1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblIziAgenda;
    private javax.swing.JLabel lblLogIn;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblSlogan;
    private javax.swing.JPanel pnlCabecera;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtRepetirContraseña;
    // End of variables declaration//GEN-END:variables
}
