/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iziagenda;

import java.awt.Component;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;

/**
 *
 * @author Angelo
 */
public class pnlCalendario extends javax.swing.JPanel {

    /**
     * Creates new form pnlCalendario
     */
    List pendientes;
    
    frmPrincipal p;
    
    GregorianCalendar fechaClickeada;
    
    public pnlCalendario(List pendientes, frmPrincipal parent)
    {
        initComponents();
        this.pendientes = pendientes;
        sleccionarMesActual();
        generarDias();
        p=parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCalendar = new javax.swing.JPanel();
        pnlMesActual = new javax.swing.JPanel();
        lblVista = new javax.swing.JLabel();
        cbMes = new javax.swing.JComboBox<>();
        lblDel = new javax.swing.JLabel();
        cbAño = new javax.swing.JComboBox<>();
        lblMesAnt = new javax.swing.JLabel();
        lblAñoAnt = new javax.swing.JLabel();
        lblMesSig = new javax.swing.JLabel();
        lblAñoSig = new javax.swing.JLabel();
        pnlMesActual1 = new javax.swing.JPanel();
        lblVista1 = new javax.swing.JLabel();
        lblVista2 = new javax.swing.JLabel();
        lblVista3 = new javax.swing.JLabel();
        lblVista4 = new javax.swing.JLabel();
        lblVista5 = new javax.swing.JLabel();
        lblVista6 = new javax.swing.JLabel();
        lblVista7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setMinimumSize(new java.awt.Dimension(1180, 580));
        setPreferredSize(new java.awt.Dimension(1180, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCalendar.setBackground(new java.awt.Color(0, 153, 204));
        pnlCalendar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        add(pnlCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1180, 480));

        pnlMesActual.setBackground(new java.awt.Color(255, 255, 255));

        lblVista.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblVista.setText("Mes:");

        cbMes.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Setiembre", "Octubre", "Noviembre", "Diciembre" }));
        cbMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMesItemStateChanged(evt);
            }
        });

        lblDel.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblDel.setText("Del:");

        cbAño.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053", "2054", "2055", "2056", "2057", "2058", "2059", "2060", "2061", "2062", "2063", "2064", "2065", "2066", "2067", "2068", "2069", "2070", "2071", "2072", "2073", "2074", "2075", "2076", "2077", "2078", "2079", "2080" }));
        cbAño.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbAñoItemStateChanged(evt);
            }
        });

        lblMesAnt.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblMesAnt.setText("<<");
        lblMesAnt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMesAnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMesAntMouseClicked(evt);
            }
        });

        lblAñoAnt.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblAñoAnt.setText("<<<");
        lblAñoAnt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAñoAnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAñoAntMouseClicked(evt);
            }
        });

        lblMesSig.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblMesSig.setText(">>");
        lblMesSig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMesSig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMesSigMouseClicked(evt);
            }
        });

        lblAñoSig.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblAñoSig.setText(">>>");
        lblAñoSig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAñoSig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAñoSigMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMesActualLayout = new javax.swing.GroupLayout(pnlMesActual);
        pnlMesActual.setLayout(pnlMesActualLayout);
        pnlMesActualLayout.setHorizontalGroup(
            pnlMesActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMesActualLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(lblAñoAnt)
                .addGap(18, 18, 18)
                .addComponent(lblMesAnt)
                .addGap(18, 18, 18)
                .addComponent(lblVista)
                .addGap(18, 18, 18)
                .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(lblDel)
                .addGap(18, 18, 18)
                .addComponent(cbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMesSig)
                .addGap(18, 18, 18)
                .addComponent(lblAñoSig)
                .addContainerGap(336, Short.MAX_VALUE))
        );
        pnlMesActualLayout.setVerticalGroup(
            pnlMesActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMesActualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMesActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMesActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAñoSig)
                        .addComponent(lblMesSig))
                    .addComponent(cbAño, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDel)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMesActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVista)
                        .addComponent(lblMesAnt)
                        .addComponent(lblAñoAnt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnlMesActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 50));

        pnlMesActual1.setBackground(new java.awt.Color(0, 153, 204));

        lblVista1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblVista1.setForeground(new java.awt.Color(255, 255, 255));
        lblVista1.setText("Lunes");

        lblVista2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblVista2.setForeground(new java.awt.Color(255, 255, 255));
        lblVista2.setText("Martes");

        lblVista3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblVista3.setForeground(new java.awt.Color(255, 255, 255));
        lblVista3.setText("Miércoles");

        lblVista4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblVista4.setForeground(new java.awt.Color(255, 255, 255));
        lblVista4.setText("Jueves");

        lblVista5.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblVista5.setForeground(new java.awt.Color(255, 255, 255));
        lblVista5.setText("Viernes");

        lblVista6.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblVista6.setForeground(new java.awt.Color(255, 255, 255));
        lblVista6.setText("Sábado");

        lblVista7.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        lblVista7.setForeground(new java.awt.Color(255, 255, 255));
        lblVista7.setText("Domingo");

        javax.swing.GroupLayout pnlMesActual1Layout = new javax.swing.GroupLayout(pnlMesActual1);
        pnlMesActual1.setLayout(pnlMesActual1Layout);
        pnlMesActual1Layout.setHorizontalGroup(
            pnlMesActual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMesActual1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVista1)
                .addGap(97, 97, 97)
                .addComponent(lblVista2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(lblVista3)
                .addGap(53, 53, 53)
                .addComponent(lblVista4)
                .addGap(86, 86, 86)
                .addComponent(lblVista5)
                .addGap(78, 78, 78)
                .addComponent(lblVista6)
                .addGap(84, 84, 84)
                .addComponent(lblVista7)
                .addGap(33, 33, 33))
        );
        pnlMesActual1Layout.setVerticalGroup(
            pnlMesActual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMesActual1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMesActual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMesActual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVista3)
                        .addComponent(lblVista4)
                        .addComponent(lblVista5)
                        .addComponent(lblVista7)
                        .addComponent(lblVista6))
                    .addGroup(pnlMesActual1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblVista1)
                        .addComponent(lblVista2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(pnlMesActual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1180, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void cbMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMesItemStateChanged
        // TODO add your handling code here:
        generarDias();
    }//GEN-LAST:event_cbMesItemStateChanged

    private void cbAñoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbAñoItemStateChanged
        // TODO add your handling code here:
        generarDias();
    }//GEN-LAST:event_cbAñoItemStateChanged

    private void lblAñoAntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAñoAntMouseClicked
        // TODO add your handling code here:
        int min=0;
        int max=cbAño.getItemCount()-1;
        int i = cbAño.getSelectedIndex();
        if(i>min)i--;
        cbAño.setSelectedIndex(i);
    }//GEN-LAST:event_lblAñoAntMouseClicked

    private void lblMesAntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMesAntMouseClicked
        // TODO add your handling code here:
        int min=0;
        int max=cbMes.getItemCount()-1;
        int i = cbMes.getSelectedIndex();
        if(i>min)
        {
            cbMes.setSelectedIndex(i-1);
        }
        else if(i==min)
        {
            if(cbAño.getSelectedIndex()>0)
            {
                cbAño.setSelectedIndex(cbAño.getSelectedIndex()-1);
                cbMes.setSelectedIndex(max);
            }
        }
    }//GEN-LAST:event_lblMesAntMouseClicked

    private void lblMesSigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMesSigMouseClicked
        // TODO add your handling code here:
        int min=0;
        int max=cbMes.getItemCount()-1;
        int i = cbMes.getSelectedIndex();
        if(i<max)
        {
            cbMes.setSelectedIndex(i+1);
        }
        else if(i==max)
        {
            if(cbAño.getSelectedIndex()<cbAño.getItemCount()-1)
            {
                cbAño.setSelectedIndex(cbAño.getSelectedIndex()+1);
                cbMes.setSelectedIndex(min);
            }
        }
    }//GEN-LAST:event_lblMesSigMouseClicked

    private void lblAñoSigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAñoSigMouseClicked
        // TODO add your handling code here:
        int min=0;
        int max=cbAño.getItemCount()-1;
        int i = cbAño.getSelectedIndex();
        if(i<max)i++;
        cbAño.setSelectedIndex(i);
    }//GEN-LAST:event_lblAñoSigMouseClicked

    public void llenarAños()
    {
        GregorianCalendar g = new GregorianCalendar();
        int año = g.get(GregorianCalendar.YEAR);
        for(int i = 0; i < 40; i++)
        {
            cbAño.addItem(String.valueOf(año++));
        }
    }
    
    public void sleccionarMesActual()
    {
        GregorianCalendar g = fabricaClass.fechaActual;
        cbMes.setSelectedIndex(g.get(GregorianCalendar.MONTH));
    }
    
    public void generarDias()
    {
        try
        {
            int año = Integer.parseInt((String)cbAño.getSelectedItem());
            int mes = cbMes.getSelectedIndex();

            GregorianCalendar g = new GregorianCalendar(año, mes, 1);
            int diaMaximo = g.getActualMaximum(GregorianCalendar.DAY_OF_MONTH);
            //System.out.println(diaMaximo);
            int posicionInicial = (g.get(GregorianCalendar.DAY_OF_WEEK) == 1)?6:g.get(GregorianCalendar.DAY_OF_WEEK) - 2;
            //System.out.println(posicionInicial);

            int d = 0;
            
            pnlCalendar.removeAll();
            
            for(int i = 0; i <42; i++)
            {
                GregorianCalendar gc = g;
                //int posicionFinal = g.get(GregorianCalendar.WEEK_OF_MONTH)-1;
                if(i<posicionInicial || i>diaMaximo+posicionInicial-1)
                {
                    pnlCalendar.add(new pnlDia());
                }
                else
                {
                    d++;
                    g = new GregorianCalendar(año, mes, d);
                    pnlDia panel = new pnlDia(g);
                    
                    /*
                    panel.addMouseListener(new java.awt.event.MouseAdapter()
                        {
                            @Override
                            public void mouseClicked(java.awt.event.MouseEvent evt)
                            {
                                presionoDia(gc);
                            }
                        }
                    );*/
                    
                    pnlCalendar.add(panel);
                }
            }
            pnlCalendar.updateUI();
            
            agregarOidores();
        }
        catch(Exception e)
        {
            //e.printStackTrace();
        }
    }

    public void presionoDia(GregorianCalendar g)
    {
        fechaClickeada = g;
    }
    
    public pnlDia[] pnlDias()
    {
        Component [] retornar = new pnlDia[42];
        int i = 0;
        for(Component c : pnlCalendar.getComponents())
        {
            retornar[i]=c;
            i++;
        }
        return (pnlDia [])retornar;
    }
    
    public JPanel getPnlCalendar()
    {
        return pnlCalendar;
    }
    
    public JComboBox getCbMes()
    {
        return cbMes;
    }
    
    public JComboBox getCbAño()
    {
        return cbAño;
    }
    
    public void agregarOidores()
    {
        p.agregarListeners(this);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbAño;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JLabel lblAñoAnt;
    private javax.swing.JLabel lblAñoSig;
    private javax.swing.JLabel lblDel;
    private javax.swing.JLabel lblMesAnt;
    private javax.swing.JLabel lblMesSig;
    private javax.swing.JLabel lblVista;
    private javax.swing.JLabel lblVista1;
    private javax.swing.JLabel lblVista2;
    private javax.swing.JLabel lblVista3;
    private javax.swing.JLabel lblVista4;
    private javax.swing.JLabel lblVista5;
    private javax.swing.JLabel lblVista6;
    private javax.swing.JLabel lblVista7;
    private javax.swing.JPanel pnlCalendar;
    private javax.swing.JPanel pnlMesActual;
    private javax.swing.JPanel pnlMesActual1;
    // End of variables declaration//GEN-END:variables
}
