/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iziagenda;

/**
 *
 * @author Angelo
 */
public class pnlDiaSinPedientes2 extends javax.swing.JPanel {

    /**
     * Creates new form pnlDiaSinPendientes
     */
    public pnlDiaSinPedientes2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPendientesDia = new javax.swing.JPanel();
        lblVista10 = new javax.swing.JLabel();
        lblVista11 = new javax.swing.JLabel();
        lblVista12 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(580, 360));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPendientesDia.setBackground(new java.awt.Color(255, 255, 255));
        pnlPendientesDia.setMaximumSize(new java.awt.Dimension(580, 360));
        pnlPendientesDia.setMinimumSize(new java.awt.Dimension(580, 360));
        pnlPendientesDia.setPreferredSize(new java.awt.Dimension(580, 360));
        pnlPendientesDia.setRequestFocusEnabled(false);
        pnlPendientesDia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVista10.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblVista10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iziagenda/Buho.gif"))); // NOI18N
        pnlPendientesDia.add(lblVista10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -20, 460, 490));

        lblVista11.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblVista11.setText("PARECE QUE NO TIENES");
        pnlPendientesDia.add(lblVista11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        lblVista12.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        lblVista12.setText("ACTIVIDADES PENDIENTES");
        pnlPendientesDia.add(lblVista12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        add(pnlPendientesDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 360));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblVista10;
    private javax.swing.JLabel lblVista11;
    private javax.swing.JLabel lblVista12;
    private javax.swing.JPanel pnlPendientesDia;
    // End of variables declaration//GEN-END:variables
}
