/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iziagenda;

import java.util.GregorianCalendar;
import javax.swing.JButton;

/**
 *
 * @author Angelo
 */
public class pnlDia extends javax.swing.JPanel {

    GregorianCalendar day;
    /**
     * Creates new form pnlDia
     */
    public pnlDia()
    {
        initComponents();
        this.day = day;
        lblDia.setText("");
        lblMas.setText("");
        
    }
    
    public pnlDia(GregorianCalendar day)
    {
        initComponents();
        this.day = day;
        int dia = day.get(GregorianCalendar.DAY_OF_MONTH);
        lblDia.setText(""+dia);
        agregarPendientes();
        
        //si es hoy cambia el fondo
        if(fabricaClass.compararFechas(day, new GregorianCalendar()))
        {
            this.setBackground(fabricaClass.turquesa);
            pnlPendientes.setBackground(fabricaClass.turquesa);
        }
    }
    
    boolean tieneDia()
    {
        return lblDia.getText()==""?false:true;
    }
    
    int numDia()
    {
        return Integer.parseInt(lblDia.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDia = new javax.swing.JLabel();
        pnlPendientes = new javax.swing.JPanel();
        lblMas = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(168, 80));
        setMinimumSize(new java.awt.Dimension(168, 80));
        setPreferredSize(new java.awt.Dimension(168, 80));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDia.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblDia.setText("Dia");
        add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pnlPendientes.setBackground(new java.awt.Color(204, 204, 255));
        pnlPendientes.setLayout(new javax.swing.BoxLayout(pnlPendientes, javax.swing.BoxLayout.Y_AXIS));
        add(pnlPendientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 120, 60));

        lblMas.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        add(lblMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 20, 20));
    }// </editor-fold>//GEN-END:initComponents

    public void agregarPendientes()
    {
        int contador = 0;
        for(PendienteClass pendiente : fabricaClass.getUsuarioLogeado().getPendientes())
        {
            if(fabricaClass.compararFechas(pendiente.getParaCuando(), this.day))
            {
                if(contador<3)
                {
                    pnlPendientes.add(new pnlPendienteEnDia(pendiente));
                    contador++;
                }
                else contador++;
            }
        }
        if(contador>3)lblMas.setText("+ " + (contador-3));
        pnlPendientes.updateUI();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblMas;
    private javax.swing.JPanel pnlPendientes;
    // End of variables declaration//GEN-END:variables
}
