/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iziagenda;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;

/**
 *
 * @author Angelo
 */
public class pnlPendiente extends javax.swing.JPanel {

    private PendienteClass pendiente;
    /**
     * Creates new form pnlPendiente
     */
    public pnlPendiente(PendienteClass pendiente)
    {
        initComponents();
        this.pendiente = pendiente;
        generarDatos();
        setColorDeFondo();
        determinarHecho();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        cbHecho = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(37, 116, 169));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(580, 80));
        setMinimumSize(new java.awt.Dimension(580, 80));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(580, 80));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        lblNombre.setText("Nombre de la tarea");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        lblFecha.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        lblFecha.setText("12:34");
        add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(37, 116, 169));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iziagenda/eliminar.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 40, 40));

        cbHecho.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbHecho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbHecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHechoActionPerformed(evt);
            }
        });
        add(cbHecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cbHechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHechoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHechoActionPerformed
/*
    public JButton getBtnEditar()
    {
        return btnEditar;
    }*/
    
    public JButton getBtnEliminar()
    {
        return btnEliminar;
    }
    
    public JCheckBox getCbHecho()
    {
        return cbHecho;
    }
    
    public void generarDatos()
    {
        lblNombre.setText(pendiente.getNombre());
        lblFecha.setText(pendiente.obtenerHora());
        
    }
    
    public PendienteClass getPendiente()
    {
        return pendiente;
    }

    public void setPendiente(PendienteClass pendiente)
    {
        this.pendiente = pendiente;
    }
    
    public void setColorDeFondo()
    {
        Color color;
        PendienteClass.Tipo tipo = pendiente.getTipo();
        
        switch(tipo)
        {
            case TAREA:
                    this.setBackground(fabricaClass.getUsuarioLogeado().getColorTarea());
                    break;
            case EXAMEN:
                    this.setBackground(fabricaClass.getUsuarioLogeado().getColorExamen());
                    break;
            case EVENTO:
                    this.setBackground(fabricaClass.getUsuarioLogeado().getColorEvento());
                    break;
            case RECORDATORIO:
                    this.setBackground(fabricaClass.getUsuarioLogeado().getColorRecordatorio());
                    break;
            default:
        }
    }
    
    public void determinarHecho()
    {
        if(pendiente.getHecho())
        {
            cbHecho.setSelected(true);
        }
        else
        {
            cbHecho.setSelected(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JCheckBox cbHecho;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
