/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iziagenda;

import java.awt.Color;

/**
 *
 * @author AngeloAlCubo
 */
public class pnlPendienteEnDia extends javax.swing.JPanel {

    PendienteClass pendiente;
    /**
     * Creates new form pnlPendienteEnDia
     */
    public pnlPendienteEnDia()
    {
        initComponents();
    }
    
    public pnlPendienteEnDia(PendienteClass pendiente)
    {
        initComponents();
        this.pendiente = pendiente;
        lblNombre.setText(pendiente.getNombre());
        setColorDeFondo();
    }
    
    
    
    public void setColorDeFondo()
    {
        Color color;
        PendienteClass.Tipo tipo = pendiente.getTipo();
        
        switch(tipo)
        {
            case TAREA:
                    this.setBackground(fabricaClass.getUsuarioLogeado().getColorTarea());
                    break;
            case EXAMEN:
                    this.setBackground(fabricaClass.getUsuarioLogeado().getColorExamen());
                    break;
            case EVENTO:
                    this.setBackground(fabricaClass.getUsuarioLogeado().getColorEvento());
                    break;
            case RECORDATORIO:
                    this.setBackground(fabricaClass.getUsuarioLogeado().getColorRecordatorio());
                    break;
            default:
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        setMaximumSize(new java.awt.Dimension(120, 20));
        setMinimumSize(new java.awt.Dimension(120, 20));
        setPreferredSize(new java.awt.Dimension(120, 20));

        lblNombre.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblNombre.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(lblNombre))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}
