/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iziagenda;

/**
 *
 * @author Angelo
 */
public class pnlUsuario extends javax.swing.JPanel {

    /**
     * Creates new form pnlUsuario
     */
    public pnlUsuario()
    {
        initComponents();
    }
    
    public pnlUsuario(usuarioClass user, int i)
    {
        initComponents();
        
        String p = String.valueOf(i);
        String puesto = (p.length()==1)?"0"+p:p;
        lblPuesto.setText(puesto);
        
        lblNombre.setText(user.getNombre());
        
        String pt = String.valueOf(user.getPuntaje());
        int l = pt.length();
        String puntaje="";
        for(int x=0;x<5;x++)
        {
            if(x>=l)puntaje+="0";
        }
        puntaje+=user.getPuntaje();
        lblPuntaje.setText(puntaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPuesto = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPuntaje = new javax.swing.JLabel();

        setBackground(new java.awt.Color(37, 116, 169));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        setMaximumSize(new java.awt.Dimension(467, 70));
        setMinimumSize(new java.awt.Dimension(467, 70));
        setPreferredSize(new java.awt.Dimension(467, 70));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPuesto.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        lblPuesto.setForeground(new java.awt.Color(255, 255, 255));
        lblPuesto.setText("##");
        add(lblPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        lblNombre.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre Apellido Apellido");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        lblPuntaje.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        lblPuntaje.setForeground(new java.awt.Color(255, 255, 255));
        lblPuntaje.setText("#####");
        add(lblPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblPuntaje;
    // End of variables declaration//GEN-END:variables
}
